// Code generated by goctl. DO NOT EDIT!

package genModel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	addressFieldNames          = builder.RawFieldNames(&Address{})
	addressRows                = strings.Join(addressFieldNames, ",")
	addressRowsExpectAutoSet   = strings.Join(stringx.Remove(addressFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	addressRowsWithPlaceHolder = strings.Join(stringx.Remove(addressFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheGoZeroMallAddressIdPrefix = "cache:goZeroMall:address:id:"
)

type (
	addressModel interface {
		Insert(ctx context.Context, data *Address) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Address, error)
		Update(ctx context.Context, newData *Address) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAddressModel struct {
		sqlc.CachedConn
		table string
	}

	Address struct {
		Id           int64     `db:"id"`
		AddTime      time.Time `db:"add_time"`
		IsDeleted    int64     `db:"is_deleted"`
		UpdateTime   time.Time `db:"update_time"`
		User         int64     `db:"user"`
		Province     string    `db:"province"`
		City         string    `db:"city"`
		District     string    `db:"district"`
		Address      string    `db:"address"`
		SignerName   string    `db:"signer_name"`
		SignerMobile string    `db:"signer_mobile"`
	}
)

func newAddressModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultAddressModel {
	return &defaultAddressModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`address`",
	}
}

func (m *defaultAddressModel) Delete(ctx context.Context, id int64) error {
	goZeroMallAddressIdKey := fmt.Sprintf("%s%v", cacheGoZeroMallAddressIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, goZeroMallAddressIdKey)
	return err
}

func (m *defaultAddressModel) FindOne(ctx context.Context, id int64) (*Address, error) {
	goZeroMallAddressIdKey := fmt.Sprintf("%s%v", cacheGoZeroMallAddressIdPrefix, id)
	var resp Address
	err := m.QueryRowCtx(ctx, &resp, goZeroMallAddressIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", addressRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAddressModel) Insert(ctx context.Context, data *Address) (sql.Result, error) {
	goZeroMallAddressIdKey := fmt.Sprintf("%s%v", cacheGoZeroMallAddressIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, addressRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.AddTime, data.IsDeleted, data.User, data.Province, data.City, data.District, data.Address, data.SignerName, data.SignerMobile)
	}, goZeroMallAddressIdKey)
	return ret, err
}

func (m *defaultAddressModel) Update(ctx context.Context, data *Address) error {
	goZeroMallAddressIdKey := fmt.Sprintf("%s%v", cacheGoZeroMallAddressIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, addressRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.AddTime, data.IsDeleted, data.User, data.Province, data.City, data.District, data.Address, data.SignerName, data.SignerMobile, data.Id)
	}, goZeroMallAddressIdKey)
	return err
}

func (m *defaultAddressModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheGoZeroMallAddressIdPrefix, primary)
}

func (m *defaultAddressModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", addressRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAddressModel) tableName() string {
	return m.table
}
