// Code generated by goctl. DO NOT EDIT!
// Source: order.proto

package server

import (
	"context"

	"zero-mal/service/order/rpc/internal/logic"
	"zero-mal/service/order/rpc/internal/svc"
	"zero-mal/service/order/rpc/pb"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

// 购物车
func (s *OrderServer) CartList(ctx context.Context, in *pb.UserInfo) (*pb.CartListResponse, error) {
	l := logic.NewCartListLogic(ctx, s.svcCtx)
	return l.CartList(in)
}

func (s *OrderServer) AddCartItem(ctx context.Context, in *pb.CartItemRequest) (*pb.ShopCartInfoResponse, error) {
	l := logic.NewAddCartItemLogic(ctx, s.svcCtx)
	return l.AddCartItem(in)
}

func (s *OrderServer) UpdateCartItem(ctx context.Context, in *pb.CartItemRequest) (*pb.Empty, error) {
	l := logic.NewUpdateCartItemLogic(ctx, s.svcCtx)
	return l.UpdateCartItem(in)
}

func (s *OrderServer) DeleteCartItem(ctx context.Context, in *pb.CartItemRequest) (*pb.Empty, error) {
	l := logic.NewDeleteCartItemLogic(ctx, s.svcCtx)
	return l.DeleteCartItem(in)
}

// 订单
func (s *OrderServer) CreateOrder(ctx context.Context, in *pb.OrderRequest) (*pb.OrderInfoResponse, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

func (s *OrderServer) OrderList(ctx context.Context, in *pb.OrderFilterRequest) (*pb.OrderListResponse, error) {
	l := logic.NewOrderListLogic(ctx, s.svcCtx)
	return l.OrderList(in)
}

func (s *OrderServer) OrderDetail(ctx context.Context, in *pb.OrderRequest) (*pb.OrderInfoDetailResponse, error) {
	l := logic.NewOrderDetailLogic(ctx, s.svcCtx)
	return l.OrderDetail(in)
}

func (s *OrderServer) UpdateOrderStatus(ctx context.Context, in *pb.OrderStatus) (*pb.Empty, error) {
	l := logic.NewUpdateOrderStatusLogic(ctx, s.svcCtx)
	return l.UpdateOrderStatus(in)
}
