Name: demo-gateway
Host: localhost
Port: 8888
Upstreams:
  - Grpc:
      Endpoints:
        - localhost:8001
    # reflection mode, no ProtoSet settings
    Mappings:
      - Method: get
        Path: /CreateUser
        RpcPath: pb.usercenter/CreateUser
#  - Grpc:
#      Etcd:
#        Hosts:
#          - localhost:2379
#        Key: hello.rpc
#    # protoset mode
#    ProtoSets:
#      - hello.pb
#    # Mappings can also be written in proto options
#    Mappings:
#      - Method: get
#        Path: /pingHello/:ping
#        RpcPath: hello.Hello/Ping