// Code generated by goctl. DO NOT EDIT!
// Source: inventory.proto

package server

import (
	"context"

	"zero-mal/service/inventory/rpc/internal/logic"
	"zero-mal/service/inventory/rpc/internal/svc"
	"zero-mal/service/inventory/rpc/inventory_pb"
)

type InventoryServer struct {
	svcCtx *svc.ServiceContext
	inventory_pb.UnimplementedInventoryServer
}

func NewInventoryServer(svcCtx *svc.ServiceContext) *InventoryServer {
	return &InventoryServer{
		svcCtx: svcCtx,
	}
}

func (s *InventoryServer) SetInv(ctx context.Context, in *inventory_pb.GoodsInvInfo) (*inventory_pb.Empty, error) {
	l := logic.NewSetInvLogic(ctx, s.svcCtx)
	return l.SetInv(in)
}

func (s *InventoryServer) InvDetail(ctx context.Context, in *inventory_pb.GoodsInvInfo) (*inventory_pb.GoodsInvInfo, error) {
	l := logic.NewInvDetailLogic(ctx, s.svcCtx)
	return l.InvDetail(in)
}

func (s *InventoryServer) Sell(ctx context.Context, in *inventory_pb.SellInfo) (*inventory_pb.Empty, error) {
	l := logic.NewSellLogic(ctx, s.svcCtx)
	return l.Sell(in)
}

func (s *InventoryServer) Reback(ctx context.Context, in *inventory_pb.SellInfo) (*inventory_pb.Empty, error) {
	l := logic.NewRebackLogic(ctx, s.svcCtx)
	return l.Reback(in)
}
