// Code generated by goctl. DO NOT EDIT!

package genModel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bannerFieldNames          = builder.RawFieldNames(&Banner{})
	bannerRows                = strings.Join(bannerFieldNames, ",")
	bannerRowsExpectAutoSet   = strings.Join(stringx.Remove(bannerFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	bannerRowsWithPlaceHolder = strings.Join(stringx.Remove(bannerFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheGoZeroMallBannerIdPrefix = "cache:goZeroMall:banner:id:"
)

type (
	bannerModel interface {
		Insert(ctx context.Context, data *Banner) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Banner, error)
		Update(ctx context.Context, newData *Banner) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBannerModel struct {
		sqlc.CachedConn
		table string
	}

	Banner struct {
		Id         int64         `db:"id"`
		AddTime    time.Time     `db:"add_time"`
		IsDeleted  sql.NullInt64 `db:"is_deleted"`
		UpdateTime time.Time     `db:"update_time"`
		Image      string        `db:"image"`
		Url        string        `db:"url"`
		Index      int64         `db:"index"`
	}
)

func newBannerModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultBannerModel {
	return &defaultBannerModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`banner`",
	}
}

func (m *defaultBannerModel) Delete(ctx context.Context, id int64) error {
	goZeroMallBannerIdKey := fmt.Sprintf("%s%v", cacheGoZeroMallBannerIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, goZeroMallBannerIdKey)
	return err
}

func (m *defaultBannerModel) FindOne(ctx context.Context, id int64) (*Banner, error) {
	goZeroMallBannerIdKey := fmt.Sprintf("%s%v", cacheGoZeroMallBannerIdPrefix, id)
	var resp Banner
	err := m.QueryRowCtx(ctx, &resp, goZeroMallBannerIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bannerRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBannerModel) Insert(ctx context.Context, data *Banner) (sql.Result, error) {
	goZeroMallBannerIdKey := fmt.Sprintf("%s%v", cacheGoZeroMallBannerIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, bannerRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.AddTime, data.IsDeleted, data.Image, data.Url, data.Index)
	}, goZeroMallBannerIdKey)
	return ret, err
}

func (m *defaultBannerModel) Update(ctx context.Context, data *Banner) error {
	goZeroMallBannerIdKey := fmt.Sprintf("%s%v", cacheGoZeroMallBannerIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, bannerRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.AddTime, data.IsDeleted, data.Image, data.Url, data.Index, data.Id)
	}, goZeroMallBannerIdKey)
	return err
}

func (m *defaultBannerModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheGoZeroMallBannerIdPrefix, primary)
}

func (m *defaultBannerModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bannerRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultBannerModel) tableName() string {
	return m.table
}
