// Code generated by goctl. DO NOT EDIT.
package types

type Loginrequest struct {
	Mobile    string `form:"mobile"  validate:"required,min=3,max=11,mobile"`
	Password  string `form:"password" validate:"required,min=5,max=10"`
	Captcha   string `form:"captcha"  validate:"required,min=5,max=5"`
	CaptchaId string `form:"captcha_id" validate:"required"`
}

type Loginresponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type Inforequest struct {
	Id int64 `form:"id" validate:"required"`
}

type Inforesponse struct {
	ID       int64  `json:"id"`
	Username string `json:"user_name"`
	NickName string `json:"nick_name"`
	Gender   string `json:"gender"`
	HeadUrl  string `json:"head_url"`
	Desc     string `json:"desc"`
}

type Createrequest struct {
	Username string `json:"user_name"`
	NickName string `json:"nick_name"`
	Gender   int    `json:"gender"`
}

type Createresponse struct {
	ID int64 `json:"id"`
}

type Editrequest struct {
	ID       int64  `json:"id"`
	Username string `json:"user_name"`
	NickName string `json:"nick_name"`
	Gender   string `json:"gender"`
}

type Editresponse struct {
}

type Logoutrequest struct {
}
